export const plateLetters = {
  persianLetters: [
    { letter: "الف", colorCode: "protocol" },
    { letter: "ب" },
    { letter: "پ", dsc: "پلیس", colorCode: "police" },
    { letter: "ت", dsc: "تاکسی", colorCode: "taxi" },
    { letter: "ث", dsc: "سپاه", colorCode: "police" },
    { letter: "ج" },
    { letter: "چ" },
    { letter: "ح" },
    { letter: "خ" },
    { letter: "د" },
    { letter: "ذ" },
    { letter: "ر" },
    { letter: "ز", dsc: "ارتش", colorCode: "navy" },
    { letter: "ژ" },
    { letter: "س" },
    { letter: "ش", dsc: "ارتش", colorCode: "army" },
    { letter: "ص" },
    { letter: "ض" },
    { letter: "ط" },
    { letter: "ظ" },
    { letter: "ع" },
    { letter: "غ" },
    { letter: "ف" },
    { letter: "ق" },
    { letter: "ک" },
    { letter: "گ" },
    { letter: "ل" },
    { letter: "م" },
    { letter: "ن" },
    { letter: "و" },
    { letter: "ه" },
    { letter: "ی" },
  ],
  englishLetters: [
    { letter: "A" },
    { letter: "D", colorCode: "service" },
    { letter: "F" },
    { letter: "P" },
    { letter: "Q" },
    { letter: "S", colorCode: "service" },
    { letter: "*" },
  ],
  symbolLetters: [{ letter: "@" }],
  numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
};
